#un = 1  n + n2  n3 + n4  n5 + n6  n7 + n8  n9 + n10


=begin

If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function, 
un = n3: 1, 8, 27, 64, 125, 216, ...

Suppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define OP(k, n) to be the nth term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that OP(k, n) will accurately generate the terms of the sequence for n  k, and potentially the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call it a bad OP (BOP).

As a basis, if we were only given the first term of sequence, it would be most sensible to assume constancy; that is, for n  2, OP(1, n) = u1.

Hence we obtain the following OPs for the cubic sequence:

OP(1, n) = 1	1, 1, 1, 1, ...
OP(2, n) = 7n6	1, 8, 15, ...
OP(3, n) = 6n211n+6     	1, 8, 27, 58, ...
OP(4, n) = n3	1, 8, 27, 64, 125, ...
Clearly no BOPs exist for k  4.

By considering the sum of FITs generated by the BOPs (indicated in red above), we obtain 1 + 15 + 58 = 74.

Consider the following tenth degree polynomial generating function:

un = 1  n + n2  n3 + n4  n5 + n6  n7 + n8  n9 + n10

Find the sum of FITs for the BOPs.

=end


require 'pp'

K = 100

@data = [];


def U(n)
  return  1 - n + n**2 - n**3 + n**4 - n**5 + n**6 - n**7 + n**8 - n**9 + n**10
end

def U2(n)
  return n**3
end


@L_cache = Hash.new(nil)

def L(x,k)
  @L_cache["#{x}:#{k}"] ||= do_L(x,k)
end


def do_L(x,k)
  total = 0
  0.upto(k-1) do |j|
    total += @data[j][1]* l(j, x, k)
  end
  return total
end

@l_cache = Hash.new(nil)

def l(j,x,k)
  @l_cache["#{j}:#{x}:#{k}"] ||= do_l(j,x,k)
end
  


def do_l(j,x,k)
  top = 1
  bot = 1
  0.upto(k-1) do |m|
    next if m == j
    top *= (x - @data[m][0])
    bot *= (@data[j][0] - @data[m][0])
  end
  return top / bot  
end


1.upto(K) do |i|
  @data << [i,U(i)]
end
pp @data
@total = 0
1.upto(K) do |k|
    guess = L(k+1,k)
    actual =  U(k+1)
    if (guess != actual)
      @total += guess
    end
end

pp @total
