=begin

An enormous factorial
Problem 288
For any prime p the number N(p,q) is defined by N(p,q) = ∑n=0 to q Tn*pn
with Tn generated by the following random number generator:

S0 = 290797
Sn+1 = Sn2 mod 50515093
Tn = Sn mod p

Let Nfac(p,q) be the factorial of N(p,q).
Let NF(p,q) be the number of factors p in Nfac(p,q).

You are given that NF(3,10000) mod 320=624955285.

Find NF(61,107) mod 6110

T0 * p**0
T1 * p**1
T2 * p**2
T3 * p**3


=end

require 'pp'



@s_cache = Hash.new
@s_cache[0] = 290797

def s(n)
  @s_cache[n] ||= do_s(n)  
end

def do_s(n)
  return s(n-1)**2 % 50515093
end

@t_cache = Hash.new
def t(n, p)
  @t_cache[n] ||= s(n) % p
end

def n(p,q)
  s = 0
  0.upto(q) do |a|
    s += t(a,p) * p**a
  end
  s
end


a = n(3,10_000)

puts a / 3.0
  