=begin

Next	
Next
Zeckendorf Representation
Problem 297
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
Starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.

Every positive integer can be uniquely written as a sum of nonconsecutive terms of the Fibonacci sequence. For example, 100 = 3 + 8 + 89.
Such a sum is called the Zeckendorf representation of the number.

For any integer n>0, let z(n) be the number of terms in the Zeckendorf representation of n.
Thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
Also, for 0<n<106, ∑ z(n) = 7894453.

Find ∑ z(n) for 0<n<1017.
=end

require 'pp'

a = 1
b = 2


c = 0

@s = []

while a <= 10**17
  @s.unshift a
  t = a+b
  a = b
  b = t
  c += 1  
end


@z_hash = Hash.new

def z(n)
  @z_hash[n] ||= do_z(n)  
end


def do_z(n)
  return 0 if n == 0
  i = 0
  while @s[i] > n
    i += 1
  end
  return 1 + z(n - @s[i])
  
      
end


k = 0

1.upto(10**17 - 1) do |i|
  k += z(i)
end

puts k

